/*

Table generated by:

//
// Generate a cosine table for the wobbly effect
//

#include <math.h>
#include <stdio.h>

static const int cycle_length = 64;
static const int amplitude = 4;
static const int nums_per_line = 16;

int main(void)
{
    printf("const int cos_table_%d_%d[] = {", cycle_length, amplitude);

    for (int i = 0; i < cycle_length; i++) {
        if (i % nums_per_line == 0) {
            printf("\n    ");
        }
        double cos_i = cos((double)i * 2.0 * M_PI / (double)cycle_length);
        int rounded = round(cos_i * amplitude) +amplitude;
        printf("%d, ", rounded);
    }
    printf("\n};\n");
    return 0;
}

*/

const int cos_table_64_4[] = {
    8, 8, 8, 8, 8, 8, 7, 7, 7, 7, 6, 6, 6, 5, 5, 4,
    4, 4, 3, 3, 2, 2, 2, 1, 1, 1, 1, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 3, 3, 4,
    4, 4, 5, 5, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 8, 8,
};
